# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy workflow

on:
  push:
    branches: [ master ]

jobs:
  job_1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: create new biuld
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd test
            git pull origin master
            yarn
            yarn build
            
